name: CI Build

on:
    push:
    pull_request:
    workflow_dispatch:
    #schedule:
    #    - cron: '42 5 * * 0'

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
#          - '5.8'
#          - '5.30'
          - '5.42'
#          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v6
      - name: Regular tests
        run: |
          perl Build.PL
          perl Build test
