name: CI

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
#    schedule:
#        - cron: '42 5 * * 0'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        perl:
          - '5.32'

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}

    steps:
    - uses: actions/checkout@v6

    - name: Set up perl
      if: ${{ startsWith( matrix.runner, 'windows-' )  }}
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry

    - name: Set up perl
      if: ${{ ! startsWith( matrix.runner, 'windows-' )  }}
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}

    - name: Install dependencies
      run: |
        cpanm --notest Dist::Zilla --verbose
        dzil authordeps --missing | cpanm --notest --verbose
        dzil listdeps --author --missing | cpanm --notest --verbose

    - name: Regular tests
      run: |
        dzil test --author --release

