name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
#          - '5.30'
          - '5.42'
#          - 'latest'
    container:
      #image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
      image: szabgab/perl     # https://github.com/szabgab/perl-docker-on-ubuntu/
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v6

      - name: Install deps
        run: |
            cpanm --quiet --installdeps --verbose --notest .

      - name: Tests
        run: |
            prove -v


