name: Sites

on:
  #push:
  #pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  generate:
    #if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    name: Generate HTML

    steps:
    - name: Generate HTML
      env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GH_TOKEN" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/szabgab/he.perlmaven.com/actions/workflows/ci.yml/dispatches \
             -d '{"ref":"main"}' | tee out.txt
        if [ -s out.txt ]
        then
            exit 1
        else
            exit 0
        fi



